import { Container } from '@nextui-org/react'
import Head from 'next/head'
import { useWindowSize } from '../../hooks/useWindowSize'
import { useRouter } from 'next/router'
import { Header } from '../../components/Header'
import { getOneLocation } from '../../services/locations'
import { CardLocation } from '../../components/CardLocation'


export default function Locations({ location }) {
  const router = useRouter()

  return (
    <div >
      <Head>
        <title>Rick and Morty APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header currentRoute={router.pathname} />

      <main >
        <Container sm css={{pt: '$10'}}>
          <CardLocation location={location} />
        </Container>
      </main>

      
    </div>
  )
}

export async function getServerSideProps({query}) {
  const location = await getOneLocation('/' + query.id)
  return {
    props: {
      location
    }
  }
}