import { Container } from '@nextui-org/react'
import Head from 'next/head'
import { CharactersContainer } from '../../components/CharactersContainer'
import { PaginationControl } from '../../components/PaginationControl'
import { useWindowSize } from '../../hooks/useWindowSize'
import { useRouter } from 'next/router'
import { Header } from '../../components/Header'
import { Search } from '../../components/Search'
import { searchCharacters } from '../../services/characters'


export default function Home({ characters, totalPages, actualPage, name, totalCount }) {
  const { width } = useWindowSize()
  const router = useRouter()


  const changePage = (page) => {
    router.push(`/search/${name}?page=${page}`)
  }

  return (
    <div >
      <Head>
        <title>Rick and Morty APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header currentRoute={router.pathname} />
      <main >
        <Container md>
          <Search initialValue={name} />
          <CharactersContainer characters={characters} total={totalCount} />
          <PaginationControl totalPages={totalPages} changePage={changePage} size={width > 500 ? 'lg' : 'xs'} initialPage={actualPage}/>
        </Container>
        
      </main>

      
    </div>
  )
}

export async function getServerSideProps({query}) {
  let actualPage = 1
  if (query.page) {
    actualPage = Number(query.page)
  }

  const {totalCount, totalPages, characters} = await searchCharacters(query.name, actualPage)
  return {
    props: {totalCount, totalPages, characters, actualPage, name: query.name}
  }
}