import { Container, Text } from '@nextui-org/react'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { CharactersContainer } from '../components/CharactersContainer'
import { PaginationControl } from '../components/PaginationControl'
import { useWindowSize } from '../hooks/useWindowSize'
import { getCharacters } from '../services/characters'
import { useRouter } from 'next/router'


export default function Home({ characters, totalPages }) {
  const [loading, setLoading] = useState(false)
  const { width } = useWindowSize()
  const router = useRouter()
  const { page } = router.query


  const changePage = (page) => {
    console.log(page)
    // setLoading(true)
    // const {charactersData} = await getCharacters(`?page=${page}`)
    // setCharacters(charactersData)
    // setLoading(false)
    
    router.push(`?page=${page}`)
    
  }

  return (
    <div >
      <Head>
        <title>Rick and Morty APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Container md>
          <Text 
          h1 
          size={45}
          color="warning"
          weight="bold">Rick and Morty APP</Text>
          <CharactersContainer characters={characters} />
          <PaginationControl totalPages={totalPages} changePage={changePage} size={width > 500 ? 'lg' : 'xs'} initialPage={page}/>
        </Container>
        
      </main>

      
    </div>
  )
}

export async function getServerSideProps({query}) {
  let url = ''
  if (query.page) url = `?page=${query.page}` 
  const {totalCount, totalPages, characters} = await getCharacters(url)
  console.log(characters)
  return {
    props: {totalCount, totalPages, characters}
  }
}